site_name: Aetheon

theme:
  name: material

nav:
  - Umbral: index.md
  - Cartografía:
      - Introducción: 03_Cartografia/README.md
      - Mapa de Aetheon: 03_Cartografia/MAPA.md

extra_css:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - assets/stylesheets/cartography.css
  - assets/stylesheets/media.css
  
extra_javascript:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - assets/javascripts/cartography.js
  - assets/javascripts/media.js
